# Nom de l'application
spring.application.name=backend

# Base de données (Compatible XAMPP Local sans mot de passe et Aiven Cloud)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configuration upload (limites de taille)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2MB

# JWT
jwt.secret=${JWT_SECRET:Gv8fRz2kLq9mXy7pTn4bWc6eHd3aJv5u}

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:99958440561-fm7jack140jhr8c2tunl9v6cqs8md4tm.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:your_google_client_secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Logs
logging.level.org.springframework.web=DEBUG
logging.level.com.ecommerce.backend=DEBUG

# Configuration Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dks3zvvga}
cloudinary.api-key=${CLOUDINARY_API_KEY:753848722798577}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:iYRqZY2fDCjz5izIvFN9-Oy3UFg}

